## 1.5 布尔索引

### 1.5.1 一维数组

In [2]:
import numpy as np
arry = np.arange(10)
print(arry)
screen = arry > 5
print(screen)   # 返回False或True
print(arry[screen])   # 返回 [6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False  True  True  True  True]
[6 7 8 9]


**实例1：把一维数组进行01化处理**

假设这10个数字，我想让大于5的数字变成1，小于等于5的数字变成0

In [3]:
arry[arry <= 5] = 0    # 小于5的赋值为0
arry[arry > 5] = 1     # 大于5的赋值为1
print(arry)

[0 0 0 0 0 0 1 1 1 1]


**实例2：进行自增量的操作，给大于5的加上520**

In [4]:
arry = np.arange(10)
arry[arry>5] += 520
print(arry)

[  0   1   2   3   4   5 526 527 528 529]


### 1.5.2 二维数组

In [5]:
arry = np.arange(1,21).reshape(4,5)
print(arry)
screen = arry>10
print(screen)         # 返回一个布尔数组，即有行又有列
print(arry[screen])    # 返回所有为True的对应数字组成的数组，以一维数组展现

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[False False False False False]
 [False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[11 12 13 14 15 16 17 18 19 20]


In [7]:
# 例：把第3例大于5的行筛选出来并重新赋值为520
arry = np.arange(1,21).reshape(4,5)
print(arry)
print("-"*30)
print(arry[:,3])  # 所有行，第3列
print("-"*30)
screen = arry[:,3] > 5  # 所有行第3列，大于5的
print(screen)
arry[screen] = 520
print(arry)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
------------------------------
[ 4  9 14 19]
------------------------------
[False  True  True  True]
[[  1   2   3   4   5]
 [520 520 520 520 520]
 [520 520 520 520 520]
 [520 520 520 520 520]]


In [8]:
arry= np.array([[10,20,30],[50,40,10],[10,1,10]])
print(arry)
screen= arry>25
print(screen)
print(arry[screen])

[[10 20 30]
 [50 40 10]
 [10  1 10]]
[[False False  True]
 [ True  True False]
 [False False False]]
[30 50 40]


**条件组合：找出偶数或小于7的数**

In [9]:
arry= np.arange(10)
print(arry)
print("-"*30)
screen = (arry%2==0) | (arry<7)
print(screen)
print("-"*30)
print(arry[screen])


[0 1 2 3 4 5 6 7 8 9]
------------------------------
[ True  True  True  True  True  True  True False  True False]
------------------------------
[0 1 2 3 4 5 6 8]
