## 3.2 swapaxes方法 【轴进行两两置换】
相当于按轴进行翻转

In [1]:
import numpy as np
arry=np.arange(24).reshape((4,6))
print(arry)
print("-"*30)
print(arry.swapaxes(1,0))


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
------------------------------
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
