## 4.5 random 生成0.0至1.0的随机数

In [1]:
import numpy as np
d1 = np.random.random(3)
print(f'生成3个0.0至1.0的随机数:\n{d1}')
d2 = np.random.random(size=(2,3))
print(f'生成2行3列共6个数的0.0至1.0的随机数:\n{d2}')
d3 = np.random.random(size=(3,2,3))
print(f'生成三块2行3列，每块6个数的0.0至1.0的随机数:\n{d3}')

生成3个0.0至1.0的随机数:
[0.57827335 0.53585466 0.89187851]
生成2行3列共6个数的0.0至1.0的随机数:
[[0.08623409 0.04335765 0.5897903 ]
 [0.13711347 0.26434175 0.24267606]]
生成三块2行3列，每块6个数的0.0至1.0的随机数:
[[[0.024504   0.20962485 0.4917007 ]
  [0.44735692 0.45380374 0.46247865]]

 [[0.070929   0.45350552 0.20297969]
  [0.52232941 0.12457884 0.72034471]]

 [[0.73553889 0.77585566 0.29371484]
  [0.96132171 0.15401922 0.92272824]]]
