## 4.8 permutation(数组)返回一个新的打乱顺序的数组

In [2]:
import numpy as np
# 与上面讲的np.random.shuffle(一维数组)效果一样,就是把一维数组重新排序了
排列 = np.random.permutation(10)    # 这里的10就看成是range(10)
print(排列)

import numpy as np
二维数组 = np.arange(9).reshape((3,3))
print(f'没有随机排列前的二维数组是\n{二维数组}\n')
排序后 = np.random.permutation(二维数组)
print(f'随机排列后的二维数组是\n{排序后}\n')
print(f'看一下原来的二维数组变了吗？\n{二维数组}')

[5 3 8 9 0 6 1 4 7 2]
没有随机排列前的二维数组是
[[0 1 2]
 [3 4 5]
 [6 7 8]]

随机排列后的二维数组是
[[3 4 5]
 [0 1 2]
 [6 7 8]]

看一下原来的二维数组变了吗？
[[0 1 2]
 [3 4 5]
 [6 7 8]]
